
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador_Lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IN_LLAVE = 17;
  public static final int NUMERO = 40;
  public static final int STRING_LITERAL = 42;
  public static final int OPE_MULT = 26;
  public static final int INT = 2;
  public static final int FOR = 10;
  public static final int MENORIGUAL = 31;
  public static final int OPE_RESTA = 25;
  public static final int AND = 33;
  public static final int OR = 34;
  public static final int COMMA = 22;
  public static final int INCREMENTO = 36;
  public static final int OPE_SUMA = 24;
  public static final int MAIN = 14;
  public static final int IF = 7;
  public static final int ID = 39;
  public static final int MAYORIGUAL = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 11;
  public static final int TRUE = 43;
  public static final int DECREMENTO = 37;
  public static final int error = 1;
  public static final int NUMERO_REAL = 41;
  public static final int NEGACION = 35;
  public static final int MENOR = 29;
  public static final int VOID = 6;
  public static final int ERROR = 38;
  public static final int ASIGNACION = 23;
  public static final int MAYOR = 28;
  public static final int FIN_PAREN = 16;
  public static final int ELSE = 8;
  public static final int FIN_CORCH = 20;
  public static final int READ = 12;
  public static final int WHILE = 9;
  public static final int FLOAT = 5;
  public static final int FIN_LLAVE = 18;
  public static final int STRING = 3;
  public static final int COMPARACION = 32;
  public static final int IN_PAREN = 15;
  public static final int IN_CORCH = 19;
  public static final int FALSE = 44;
  public static final int TERMINADOR = 21;
  public static final int PRINT = 13;
  public static final int OPE_DIV = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "STRING",
  "BOOLEAN",
  "FLOAT",
  "VOID",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "READ",
  "PRINT",
  "MAIN",
  "IN_PAREN",
  "FIN_PAREN",
  "IN_LLAVE",
  "FIN_LLAVE",
  "IN_CORCH",
  "FIN_CORCH",
  "TERMINADOR",
  "COMMA",
  "ASIGNACION",
  "OPE_SUMA",
  "OPE_RESTA",
  "OPE_MULT",
  "OPE_DIV",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "COMPARACION",
  "AND",
  "OR",
  "NEGACION",
  "INCREMENTO",
  "DECREMENTO",
  "ERROR",
  "ID",
  "NUMERO",
  "NUMERO_REAL",
  "STRING_LITERAL",
  "TRUE",
  "FALSE"
  };
}

